DROP TABLE IF EXISTS addresses;

CREATE TABLE addresses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    province VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    details VARCHAR(100) NOT NULL,
    mobile VARCHAR(100) NOT NULL,
    postcode VARCHAR(100) NOT NULL,
    contact VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    longitude VARCHAR(100) NOT NULL,
    latitude VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO
    addresses OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        'Waikato',
        'Hamilton',
        '21 Comries Road, Chartwell',
        '02902574384',
        '3210',
        'Chandler Li',
        'ChandlerNZLee@outlook.com',
        '175.26924509725518',
        '-37.75341433355246'
    );

INSERT INTO
    addresses OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        'Waikato',
        'Hamilton',
        '3 Rutland Street, Fairview Downs',
        '02902574384',
        '3214',
        'Chandler Li',
        'ChandlerNZLee@outlook.com',
        '175.29986083958454',
        '-37.76042611436126'
    );