-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS appointments;

CREATE TABLE appointments (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    pet_id INTEGER NOT NULL,
    shop_id INTEGER NOT NULL,
    room_id INTEGER NOT NULL,
    groomer_id INTEGER NOT NULL,
    origin_price DECIMAL(10, 2) NOT NULL,
    discount DECIMAL(10, 2) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    payment_status INTEGER NOT NULL,
    appointment_status INTEGER NOT NULL,
    notes VARCHAR(255) NOT NULL
);