-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS appointment_slots;
CREATE TABLE appointment_slots (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  appointment_id INTEGER NOT NULL,
  slot_id INTEGER NOT NULL,
  PRIMARY KEY (id)
);