-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS appointment_services;

CREATE TABLE appointment_services (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id INTEGER NOT NULL,
    service_id INTEGER NOT NULL
);