-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS groomers;
CREATE TABLE groomers (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  shop_id INTEGER NOT NULL,
  name VARCHAR(100) NOT NULL,
  type INTEGER NOT NULL,
  experience INTEGER NOT NULL,
  customers INTEGER NOT NULL,
  description VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ;

ALTER TABLE groomers
ADD CONSTRAINT fk_groomers_shop
FOREIGN KEY (shop_id) REFERENCES shops(id);

INSERT INTO groomers OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 1, 'Emily Zhang', 0, 8, 128, 'Specializes in gentle handling and anxiety-free grooming for all pets.');
INSERT INTO groomers OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 1, 'Michael Chen', 0, 6, 96, 'Expert in breed-specific styling and coat care.');
INSERT INTO groomers OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 1, 'Sophia Lee', 1, 2, 78, 'Great with active pets and gentle grooming.');
INSERT INTO groomers OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 1, 'Michael Chen', 1, 2, 62, 'Patient and attentive, loves all pets.');
