-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS pets;
CREATE TABLE pets (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  avatar VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  gender INTEGER NOT NULL,
  category INTEGER NOT NULL,
  fur_type INTEGER NOT NULL,
  birthday VARCHAR(100) NOT NULL,
  activation_status INTEGER NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO pets OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 3, 'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240713123138.jpg', 'Little Bao', 0, 0, 0, '2011-05-01', 1);
INSERT INTO pets OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 4, 'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/2024072011525000.jpg', 'Muffin', 0, 1, 0, '2024-05-04', 1);
INSERT INTO pets OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 5, 'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240705132052118.jpg', 'Simba', 0, 1, 0, '2024-05-04', 1);
INSERT INTO pets OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 6, 'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240711205729265.jpg', 'Keke', 1, 0, 0, '2024-05-04', 1);
INSERT INTO pets OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 7, 'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240713171821036.jpg', 'Lisa', 1, 0, 0, '2014-06-01', 1);
INSERT INTO pets OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 8, 'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20250515174554231.jpg', 'Mika', 1, 0, 0, '2016-10-19', 1);