-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS product_images;

CREATE TABLE product_images (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL,
    url VARCHAR(255) NOT NULL,
    sort_order INTEGER NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE product_images
ADD CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products (id);

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165429552.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165432853.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165436187.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165440837.jpg',
        3
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165505584.jpg',
        4
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165155409.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165149214.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165152459.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165146207.jpg',
        3
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621230828953.jpg',
        4
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621230831335.jpg',
        5
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621230834031.jpg',
        6
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165058563.png',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165101678.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165104958.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165029257.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165032504.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165035810.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627165042680.jpg',
        3
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240628103255086.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240628103302353.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240628103305535.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240628103309064.jpg',
        3
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240628103311630.jpg',
        4
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164742648.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164745619.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164750499.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164753413.jpg',
        3
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164758407.jpg',
        4
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164801542.jpg',
        5
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164815735.jpg',
        6
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164819713.jpg',
        7
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164823034.jpg',
        8
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164832197.jpg',
        9
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164836556.jpg',
        10
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164841902.jpg',
        11
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164847582.jpg',
        12
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164546452.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164550731.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164556002.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164559074.jpg',
        3
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164604081.jpg',
        4
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164630785.jpg',
        5
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164633532.jpg',
        6
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164637897.jpg',
        7
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164641366.jpg',
        8
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164644403.jpg',
        9
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164647939.jpg',
        10
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164650954.jpg',
        11
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164455795.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164504320.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164512841.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164515561.jpg',
        3
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164447058.jpg',
        4
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164450836.jpg',
        5
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164225717.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164228943.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164232391.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164236020.jpg',
        3
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164248713.jpg',
        4
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164252324.jpg',
        5
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621230624748.png',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240618134713332.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621223253425.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621223307902.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621230545178.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621230550342.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621230554482.jpg',
        2
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621230557868.jpg',
        3
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240621230603565.jpg',
        4
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164144854.jpg',
        0
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164141762.jpg',
        1
    );

INSERT INTO
    product_images OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240627164147710.jpg',
        2
    );