-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS product_stocks;

CREATE TABLE product_stocks (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL,
    shop_id INTEGER NOT NULL,
    size VARCHAR(100) NOT NULL,
    stock INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    discount DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE product_stocks
ADD CONSTRAINT fk_product_stocks_product FOREIGN KEY (product_id) REFERENCES products (id);

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        'Mixed Pack',
        1000,
        58.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        'Cranberry Flavor',
        1000,
        58.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        'Duck & Pear Flavor',
        1000,
        58.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        'Milk Calcium',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        'Pumpkin',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        'Egg Yolk',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        'Chicken & Pumpkin',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        'Beef Dragon Fruit',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        'Cod & Spinach',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        'Chicken & Apple & Brown Algae',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        'Chicken & Papaya & Turmeric',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        'Chicken & Blueberry & Sea Buckthorn',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        'Beef Recipe',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        'Turkey Recipe',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        'Salmon Recipe',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        1,
        'Chicken Steak',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        1,
        'Beef Steak',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        1,
        'Beef Roll',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        1,
        'Chicken Wrap',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        1,
        'Duck Flavor',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        1,
        'Chicken Flavor',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        'Chicken Wrapped with Egg Yolk 80g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        'Duck Wrapped around Snow Pear 70g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        'Duck Cooked with Sweet Potatoes 135g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        'Chicken Breast & Pumpkin 25g*6',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        'Duck Meat Beef Roll 100g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        1,
        'Pure Meat Egg Yolk Roll 75g',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        1,
        'Chicken Slices 60g',
        1000,
        24.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        'Fragrant Roasted Beef Bone Combo 500g',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        'Large Beef Shank Bone 430g',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        'Crispy Beef Short Ribs 120g',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        1,
        'Chicken & Broccoli',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        1,
        'Pumpkin',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        1,
        'Cod & Pumpkin',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        1,
        'Cod slices',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        1,
        'Cod & Pumpkin',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        1,
        'Cod slices',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        15,
        1,
        'Mini Tuna Strips',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        15,
        1,
        'Mini Chicken Strips',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        15,
        1,
        'Chicken Strips',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        15,
        1,
        'Duck Strips',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        16,
        1,
        'Honey Cheese Stick 58g',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        16,
        1,
        'Chicken, Veggie, & Cheese Bone 65g',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        17,
        1,
        'Chicken & Turkey Rings',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        17,
        1,
        'Duck Rings',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        18,
        1,
        'Mango Flavor',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        18,
        1,
        'Kiwi Flavor',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        19,
        1,
        'Chicken Banana Flavor',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        19,
        1,
        'Chicken Blueberry Flavor',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        20,
        1,
        'Braised Duck - Good for Your Eyes',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        20,
        1,
        'Braised Beef - Gentle on the Stomach',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        20,
        1,
        'Braised Quail Eggs - Shiny Fur',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        20,
        1,
        'Braised Chicken - Caring for Your Urinary Health',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        21,
        1,
        'Beef-Fish Skin Moisturizer',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        21,
        1,
        'Cat Grass - Healthy Hairball Control',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        22,
        1,
        'Duck Wrapped around Snow Pear 70g',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        22,
        1,
        'Chicken Wrapped around Pumpkin 70g',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        22,
        1,
        'Beef Throat Tube 70g',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        22,
        1,
        'Chicken & Cod Skin 90g',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        22,
        1,
        'Chicken & Beef Chew Stick 100g',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        22,
        1,
        'Beef Tongue 70g',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        23,
        1,
        'Green Vegetables 25g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        23,
        1,
        'Dietary fiber 35g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        23,
        1,
        'Berries 25g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        23,
        1,
        'Purple Vegetable 25g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        23,
        1,
        'Mixed Fruit 25g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        24,
        1,
        'Egg Yolk Cod Skin - Large Dog',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        24,
        1,
        'Egg Yolk Cod Skin - Small Dog',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        24,
        1,
        'Chicken & Cod Skin - Small Dog',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        25,
        1,
        '40g',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        26,
        1,
        'Beet',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        26,
        1,
        'Egg Yolk Coconut',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        26,
        1,
        'Purple Sweet Potato',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        26,
        1,
        'Green Juice',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        27,
        1,
        'Tender Chicken Breast Raw Beef Hide Stick',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        27,
        1,
        'Mini Chicken Breast Raw Beef Roll',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        27,
        1,
        'Chicken Breast Wrapped in Raw Beef Skin',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        27,
        1,
        'Chewy Biscuit Chicken Roll',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        27,
        1,
        'Tooth Grinding Biscuit Duck Roll',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        28,
        1,
        'Dried Duck',
        1000,
        24.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        28,
        1,
        'Dried Chicken',
        1000,
        24.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        29,
        1,
        '35g*6/bag',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        29,
        1,
        '35g*30/box',
        1000,
        128.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        30,
        1,
        'Chicken Wrapped with Cheese 120g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        30,
        1,
        'Chicken Wrapped with Coconut 80g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        30,
        1,
        'Duck Wrapped around Snow Pear 100g',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        31,
        1,
        'Beef',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        31,
        1,
        'Rabbit',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        31,
        1,
        'Chicken',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        31,
        1,
        'Duck',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        32,
        1,
        '90g',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        33,
        1,
        'Deer Flavor',
        1000,
        15.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        33,
        1,
        'Rabbit Flavor',
        1000,
        15.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        33,
        1,
        'Pigeon Flavor',
        1000,
        15.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        34,
        1,
        'Iron Pot Stewed Goose',
        1000,
        12.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        34,
        1,
        'Steamed Salmon',
        1000,
        12.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        34,
        1,
        'Clear Stew Prairie Lamb',
        1000,
        12.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        34,
        1,
        'Steamed Hill Chicken',
        1000,
        12.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        35,
        1,
        'Chicken & Snow Pear & Glehnia Cat Sticks',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        35,
        1,
        'Chicken & Kiwi & Bupleurum Cat Sticks',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        35,
        1,
        'Chicken & Mulberry & Goji Cat Sticks',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        35,
        1,
        'Chicken & Blueberry & Astragalus Cat Sticks',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        35,
        1,
        'Chicken & Pineapple & Atractylodes Cat Sticks',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        36,
        1,
        'Turkey Recipe',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        36,
        1,
        'Goose Meat Recipe',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        36,
        1,
        'Rabbit Meat Recipe',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        36,
        1,
        'Duck Recipe',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        36,
        1,
        'Salmon Recipe',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        37,
        1,
        'Tuna + Whitebait + Bonito flakes',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        37,
        1,
        'Tuna + Chicken + Beef',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        37,
        1,
        'Tuna',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        38,
        1,
        'Rabbit Flavor',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        38,
        1,
        'Chicken Flavor',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        39,
        1,
        'Krill Extract',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        39,
        1,
        'Cat Grass Pulp',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        39,
        1,
        'Deep-sea Kelp',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        40,
        1,
        'Chicken and fish oil flavor',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        40,
        1,
        'Rabbit meat and colostrum flavor',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        40,
        1,
        'Pigeon Meat Cranberry Flavor',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        41,
        1,
        'Tooth cleaning ball',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        41,
        1,
        'Cat pillow',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        42,
        1,
        'Chicken, tuna, scallops',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        42,
        1,
        'Chicken with silverfish',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        42,
        1,
        'Chicken and cod',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        42,
        1,
        'Chicken and shrimp',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        42,
        1,
        'Chicken, salmon, fish oil',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        42,
        1,
        'Chicken and crab meat',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        43,
        1,
        '85g * 7/box',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        44,
        1,
        'Chicken and goat milk',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        44,
        1,
        'Chicken and beef',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        44,
        1,
        'Tuna roe',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        44,
        1,
        'Tuna Catnip',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        45,
        1,
        'Chicken and goat milk',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        46,
        1,
        '8g',
        1000,
        3.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        47,
        1,
        '110ml',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        47,
        1,
        '110ml * 6/box',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        48,
        1,
        '110ml',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        48,
        1,
        '110ml * 6/box',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        49,
        1,
        'Tuna Recipe',
        1000,
        8.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        49,
        1,
        'Chicken Recipe',
        1000,
        8.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        49,
        1,
        'Deer Recipe',
        1000,
        8.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        49,
        1,
        'Beef Recipe',
        1000,
        8.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        50,
        1,
        'Beef',
        1000,
        108.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        50,
        1,
        'Chicken',
        1000,
        108.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        51,
        1,
        'Beef & Salmon',
        1000,
        88.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        51,
        1,
        'Chicken & Salmon',
        1000,
        88.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        52,
        1,
        '1.36kg',
        1000,
        118.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        53,
        1,
        '1.5kg',
        1000,
        118.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        54,
        1,
        'Beef',
        1000,
        108.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        54,
        1,
        'Chicken',
        1000,
        108.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        55,
        1,
        'Beef and Chinese yam',
        1000,
        88.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        55,
        1,
        'Chicken and oats',
        1000,
        88.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        56,
        1,
        '1.36kg',
        1000,
        108.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        57,
        1,
        'Blue',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        57,
        1,
        'Pink',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        58,
        1,
        'Brother Rabbit',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        58,
        1,
        'Little Bunnny Brother',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        58,
        1,
        'Stupid Ape',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        58,
        1,
        'Cute Little Elephant',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        58,
        1,
        'The Parrot of Rio',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        58,
        1,
        'Noisy Parrot',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        58,
        1,
        'Afanti Donkey',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        58,
        1,
        'Spicy Rabbit Head',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        59,
        1,
        'Peacock Green',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        59,
        1,
        'Crimson Leaves',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        60,
        1,
        'Blue heart',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        60,
        1,
        'Colorful heart',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        60,
        1,
        'Colorful circle',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        61,
        1,
        'Dragonfly-like cherry blossom feather',
        1000,
        7.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        61,
        1,
        'Dragonfly-like green feather',
        1000,
        7.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        61,
        1,
        'Dragonfly-like apricot yellow feather',
        1000,
        7.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        61,
        1,
        'Dragonfly-like silver-gray feather',
        1000,
        7.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        61,
        1,
        'Dragonfly-like crimson feather',
        1000,
        7.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        62,
        1,
        'Yellow',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        62,
        1,
        'Orange',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        62,
        1,
        'Sky blue',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        62,
        1,
        'Soft feather color',
        1000,
        9.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        63,
        1,
        'Purple',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        63,
        1,
        'Light blue',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        63,
        1,
        'Dark blue',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        63,
        1,
        'Gold',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        63,
        1,
        'Black',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        63,
        1,
        'White',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        63,
        1,
        'Yellow',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        63,
        1,
        'Green',
        1000,
        5.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        64,
        1,
        'Vibrant Purple',
        1000,
        15.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        64,
        1,
        'Grassland Green',
        1000,
        15.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        65,
        1,
        'Original G-Ball',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        65,
        1,
        'Cheese Dental Chew',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        65,
        1,
        'Big Cookie Man Dental Chew',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        66,
        1,
        'Rattan Ball Bell Bear',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        66,
        1,
        'Rattan Ball Bell Mouse',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        66,
        1,
        'Dazzling Rhythm Prey Hedgehog',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        67,
        1,
        'S',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        67,
        1,
        'M',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        67,
        1,
        'L',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        68,
        1,
        'L',
        1000,
        45.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        69,
        1,
        'S',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        69,
        1,
        'L',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        70,
        1,
        'S',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        70,
        1,
        'L',
        1000,
        58.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        71,
        1,
        'L',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        72,
        1,
        'XL',
        1000,
        68.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        73,
        1,
        'S',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        74,
        1,
        'XL',
        1000,
        68.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        75,
        1,
        'S',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        75,
        1,
        'L',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        76,
        1,
        'S',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        76,
        1,
        'XL',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        77,
        1,
        'Honey yellow',
        1000,
        58.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        77,
        1,
        'Teal',
        1000,
        58.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        78,
        1,
        'Red checkered bow',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        78,
        1,
        'Blue plaid bow',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        79,
        1,
        'Blue Plaid Cherry Embroidery, Size M',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        79,
        1,
        'Yellow Plaid Pineapple Embroidery, Size S',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        80,
        1,
        'Pink puppy',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        80,
        1,
        'Yellow puppy',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        80,
        1,
        'Blue puppy',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        80,
        1,
        'Green puppy',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        81,
        1,
        'Gray puppy',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        81,
        1,
        'Blue puppy',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        82,
        1,
        'Green',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        82,
        1,
        'Pink',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        83,
        1,
        'XL',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        84,
        1,
        'L',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        84,
        1,
        'M',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        85,
        1,
        'Green',
        1000,
        158.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        85,
        1,
        'Coffee',
        1000,
        158.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        85,
        1,
        'Pink',
        1000,
        158.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        86,
        1,
        '15mg per tablet',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        87,
        1,
        '2.5ml per tube',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        88,
        1,
        '0.25ml per tube',
        1000,
        68.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        89,
        1,
        'Weight < 10kg',
        1000,
        68.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        89,
        1,
        '20 < Weight < 40kg',
        1000,
        78.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        90,
        1,
        'Kitten',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        90,
        1,
        'Adult cat',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        91,
        1,
        '60ml/box',
        1000,
        58.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        92,
        1,
        '60ml/box',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        93,
        1,
        '50ml/box',
        1000,
        68.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        94,
        1,
        '6g/bag * 10',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        95,
        1,
        'WK-6',
        1000,
        12.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        96,
        1,
        'L',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        97,
        1,
        'Blue',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        98,
        1,
        '60cm*90cm*22 pieces (L)',
        1000,
        45.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        98,
        1,
        '45cm*60cm*50 pieces (M)',
        1000,
        45.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        98,
        1,
        '45cm*33cm*100 pieces (S)',
        1000,
        45.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        99,
        1,
        '200 pieces',
        1000,
        88.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        100,
        1,
        '200 pieces',
        1000,
        88.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        101,
        1,
        '200 pieces',
        1000,
        88.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        102,
        1,
        'Hairball paste',
        1000,
        88.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        102,
        1,
        'Cat ointment',
        1000,
        88.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        103,
        1,
        'Calcium Peptide Ointment',
        1000,
        88.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        104,
        1,
        'Watermelon flavor',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        104,
        1,
        'Cherry blossom flavor',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        104,
        1,
        'Forest flavor',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        104,
        1,
        'Peach flavor',
        1000,
        38.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        105,
        1,
        'Light blue',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        105,
        1,
        'Coffee',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        106,
        1,
        'Snail Blue',
        1000,
        68.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        106,
        1,
        'Blush',
        1000,
        68.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        107,
        1,
        'Moist Jade Blue',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        107,
        1,
        'Crystal Green',
        1000,
        48.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        108,
        1,
        'Pink',
        1000,
        108.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        108,
        1,
        'Gray',
        1000,
        108.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        109,
        1,
        'XS',
        1000,
        15.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        109,
        1,
        'S',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        109,
        1,
        'M',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        109,
        1,
        'L',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        109,
        1,
        'XL',
        1000,
        32.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        110,
        1,
        'S',
        1000,
        18.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        110,
        1,
        'M',
        1000,
        22.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        110,
        1,
        'L',
        1000,
        28.00,
        1.00
    );

INSERT INTO
    product_stocks OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        110,
        1,
        'XL',
        1000,
        32.00,
        1.00
    );