-- Active: 1786433062240@@127.0.0.1@5432@yipethome
-- Active: 1784193694048@@127.0.0.1@3306@mysql
DROP TABLE IF EXISTS recharge_bonuses;
CREATE TABLE recharge_bonuses (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  recharge_amount INTEGER NOT NULL,
  gift_amount INTEGER NOT NULL,
  activation_status INTEGER NOT NULL,
  sort_order INTEGER NOT NULL,
  PRIMARY KEY (id)
) ;

INSERT INTO recharge_bonuses OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 'Silver Member', 500, 200, 1, 0);
INSERT INTO recharge_bonuses OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 'Golden Member', 1000, 520, 1, 1);
INSERT INTO recharge_bonuses OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 'Black Golden Member', 3000, 2000, 1, 2);