-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS recharge_records;
CREATE TABLE recharge_records (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  bonus_id INTEGER NOT NULL,
  balance_before DECIMAL(10, 2) NOT NULL,
  balance_after DECIMAL(10, 2) NOT NULL,
  create_time VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
) ;