-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS services;

CREATE TABLE services (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type INTEGER NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        0,
        'Regular Wash & Care',
        'Regular Wash & Care',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        0,
        'Ultra Bright Custom Hair Care',
        'Ultra Bright Custom Hair Care',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        0,
        'Fluffy Competition-Grade Custom Shampoo & Care',
        'Fluffy Competition-Grade Custom Shampoo & Care',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        0,
        'Oil-Control Skin Refreshing Customized Care',
        'Oil-Control Skin Refreshing Customized Care',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        0,
        'Refreshing Anti-Dandruff Customized Hair Care',
        'Refreshing Anti-Dandruff Customized Hair Care',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        0,
        'Hypoallergenic Care Custom Shampoo & Conditioner',
        'Hypoallergenic Care Custom Shampoo & Conditioner',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        0,
        'Deep Hydration Custom Hair Care',
        'Deep Hydration Custom Hair Care',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        0,
        'Antibacterial and Stability-Enhancing Hair Care',
        'Antibacterial and Stability-Enhancing Hair Care',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        'Custom Styling',
        'Custom Styling',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'Regenerative Purifying SPA',
        'Regenerative Purifying SPA',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'Soothing Skin-Repairing Essence',
        'Soothing Skin-Repairing Essence',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'Antibacterial Repair SPA',
        'Antibacterial Repair SPA',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'Shiny Smooth Hair Mask SPA',
        'Shiny Smooth Hair Mask SPA',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        'Repair and Restore SPA',
        'Repair and Restore SPA',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        'Teeth Brushing',
        'Helps reduce plaque and promotes fresh breath.',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        'Deodorizing Treatment',
        'Eliminates odors and leaves a long-lasting fresh scent.',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        'Paw Balm',
        'Moisturizes and protects dry, cracked paw pads.',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        'Sanitary Trim',
        'Hygienic trimming for the private area.',
        ''
    );

INSERT INTO
    services OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        'Bow or Bandana',
        'Cute accessory to make your pet look even more adorable.',
        ''
    );