-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS service_prices;

CREATE TABLE service_prices (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    service_id INTEGER NOT NULL,
    category INTEGER NOT NULL,
    fur_type INTEGER NOT NULL,
    duration INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    weight_from INTEGER NOT NULL,
    weight_to INTEGER NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE service_prices
ADD CONSTRAINT fk_service_prices_service FOREIGN KEY (service_id) REFERENCES services (id);

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        0,
        1,
        40.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        1,
        1,
        40.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        0,
        2,
        60.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        1,
        2,
        60.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        0,
        2,
        80.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        1,
        2,
        80.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        0,
        2,
        110.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        1,
        2,
        110.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        0,
        3,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        1,
        3,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        0,
        3,
        180.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        1,
        3,
        180.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        0,
        4,
        220.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        0,
        1,
        4,
        220.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        0,
        2,
        80.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        1,
        2,
        90.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        0,
        3,
        120.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        1,
        4,
        140.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        0,
        4,
        140.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        1,
        4,
        180.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        0,
        4,
        180.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        1,
        1,
        1,
        5,
        230.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        0,
        2,
        88.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        1,
        2,
        88.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        0,
        3,
        108.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        1,
        3,
        108.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        0,
        3,
        158.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        1,
        3,
        158.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        0,
        3,
        208.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        1,
        3,
        208.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        0,
        4,
        258.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        1,
        4,
        258.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        0,
        4,
        308.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        1,
        4,
        308.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        0,
        5,
        358.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        0,
        1,
        5,
        358.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        0,
        3,
        128.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        1,
        3,
        138.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        0,
        4,
        168.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        1,
        5,
        208.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        0,
        5,
        188.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        1,
        5,
        258.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        0,
        5,
        218.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        2,
        1,
        1,
        6,
        298.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        0,
        2,
        88.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        1,
        2,
        88.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        0,
        3,
        108.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        1,
        3,
        108.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        0,
        3,
        158.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        1,
        3,
        158.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        0,
        3,
        208.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        1,
        3,
        208.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        0,
        4,
        258.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        1,
        4,
        258.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        0,
        4,
        308.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        1,
        4,
        308.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        0,
        5,
        358.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        0,
        1,
        5,
        358.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        0,
        3,
        128.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        1,
        3,
        138.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        0,
        4,
        168.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        1,
        5,
        208.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        0,
        5,
        188.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        1,
        5,
        258.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        0,
        5,
        218.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        3,
        1,
        1,
        6,
        298.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        0,
        2,
        108.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        1,
        2,
        108.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        0,
        3,
        128.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        1,
        3,
        128.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        0,
        3,
        178.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        1,
        3,
        178.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        0,
        3,
        228.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        1,
        3,
        228.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        0,
        4,
        278.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        1,
        4,
        278.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        0,
        4,
        328.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        1,
        4,
        328.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        0,
        5,
        378.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        0,
        1,
        5,
        378.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        0,
        3,
        148.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        1,
        3,
        158.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        0,
        4,
        188.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        1,
        5,
        228.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        0,
        5,
        208.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        1,
        5,
        278.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        0,
        5,
        238.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        4,
        1,
        1,
        6,
        318.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        0,
        2,
        88.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        1,
        2,
        88.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        0,
        3,
        108.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        1,
        3,
        108.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        0,
        3,
        158.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        1,
        3,
        158.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        0,
        3,
        208.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        1,
        3,
        208.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        0,
        4,
        258.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        1,
        4,
        258.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        0,
        4,
        308.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        1,
        4,
        308.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        0,
        5,
        358.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        0,
        1,
        5,
        358.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        0,
        3,
        128.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        1,
        3,
        138.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        0,
        4,
        168.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        1,
        5,
        208.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        0,
        5,
        188.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        1,
        5,
        258.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        0,
        5,
        218.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        5,
        1,
        1,
        6,
        298.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        0,
        2,
        88.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        1,
        2,
        88.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        0,
        3,
        108.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        1,
        3,
        108.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        0,
        3,
        158.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        1,
        3,
        158.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        0,
        3,
        208.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        1,
        3,
        208.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        0,
        4,
        258.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        1,
        4,
        258.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        0,
        4,
        308.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        1,
        4,
        308.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        0,
        5,
        358.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        0,
        1,
        5,
        358.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        1,
        0,
        3,
        128.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        1,
        1,
        3,
        138.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        1,
        0,
        4,
        168.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        1,
        1,
        5,
        208.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        1,
        0,
        5,
        188.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        1,
        1,
        5,
        258.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        1,
        0,
        5,
        218.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        6,
        1,
        1,
        6,
        298.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        0,
        2,
        88.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        1,
        2,
        88.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        0,
        3,
        108.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        1,
        3,
        108.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        0,
        3,
        158.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        1,
        3,
        158.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        0,
        3,
        208.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        1,
        3,
        208.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        0,
        4,
        258.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        1,
        4,
        258.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        0,
        4,
        308.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        1,
        4,
        308.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        0,
        5,
        358.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        0,
        1,
        5,
        358.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        1,
        0,
        3,
        128.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        1,
        1,
        3,
        138.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        1,
        0,
        4,
        168.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        1,
        1,
        5,
        208.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        1,
        0,
        5,
        188.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        1,
        1,
        5,
        258.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        1,
        0,
        5,
        218.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        7,
        1,
        1,
        6,
        298.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        0,
        2,
        108.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        1,
        2,
        108.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        0,
        3,
        128.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        1,
        3,
        128.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        0,
        3,
        178.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        1,
        3,
        178.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        0,
        3,
        228.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        1,
        3,
        228.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        0,
        4,
        278.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        1,
        4,
        278.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        0,
        4,
        328.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        1,
        4,
        328.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        0,
        5,
        378.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        0,
        1,
        5,
        378.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        1,
        0,
        3,
        148.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        1,
        1,
        3,
        158.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        1,
        0,
        4,
        188.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        1,
        1,
        5,
        228.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        1,
        0,
        5,
        208.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        1,
        1,
        5,
        278.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        1,
        0,
        5,
        238.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        8,
        1,
        1,
        6,
        318.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        0,
        3,
        68.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        1,
        3,
        68.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        0,
        3,
        68.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        1,
        3,
        68.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        0,
        3,
        88.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        1,
        3,
        88.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        0,
        3,
        98.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        1,
        3,
        98.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        0,
        3,
        148.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        1,
        3,
        148.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        0,
        3,
        178.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        1,
        3,
        178.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        0,
        3,
        238.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        0,
        1,
        3,
        238.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        0,
        999,
        999.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        1,
        999,
        999.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        0,
        999,
        999.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        1,
        999,
        999.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        0,
        999,
        999.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        1,
        999,
        999.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        0,
        999,
        999.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        9,
        1,
        1,
        999,
        999.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        0,
        1,
        60.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        1,
        1,
        60.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        0,
        1,
        80.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        1,
        1,
        80.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        0,
        1,
        120.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        1,
        1,
        120.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        0,
        1,
        130.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        1,
        1,
        130.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        0,
        1,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        1,
        1,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        0,
        1,
        160.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        1,
        1,
        160.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        0,
        1,
        180.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        0,
        1,
        1,
        180.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        1,
        0,
        1,
        118.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        1,
        1,
        1,
        118.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        1,
        0,
        1,
        158.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        1,
        1,
        1,
        158.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        1,
        0,
        1,
        178.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        1,
        1,
        1,
        178.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        1,
        0,
        1,
        198.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        10,
        1,
        1,
        1,
        198.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        0,
        1,
        60.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        1,
        1,
        60.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        0,
        1,
        80.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        1,
        1,
        80.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        0,
        1,
        120.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        1,
        1,
        120.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        0,
        1,
        130.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        1,
        1,
        130.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        0,
        1,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        1,
        1,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        0,
        1,
        160.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        1,
        1,
        160.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        0,
        1,
        180.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        0,
        1,
        1,
        180.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        0,
        1,
        118.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        1,
        1,
        118.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        0,
        1,
        158.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        1,
        1,
        158.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        0,
        1,
        178.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        1,
        1,
        178.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        0,
        1,
        198.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        11,
        1,
        1,
        1,
        198.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        0,
        1,
        60.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        1,
        1,
        60.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        0,
        1,
        80.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        1,
        1,
        80.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        0,
        1,
        120.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        1,
        1,
        120.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        0,
        1,
        130.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        1,
        1,
        130.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        0,
        1,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        1,
        1,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        0,
        1,
        160.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        1,
        1,
        160.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        0,
        1,
        180.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        0,
        1,
        1,
        180.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        1,
        0,
        1,
        118.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        1,
        1,
        1,
        118.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        1,
        0,
        1,
        158.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        1,
        1,
        1,
        158.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        1,
        0,
        1,
        178.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        1,
        1,
        1,
        178.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        1,
        0,
        1,
        198.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        12,
        1,
        1,
        1,
        198.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        0,
        1,
        60.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        1,
        1,
        60.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        0,
        1,
        80.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        1,
        1,
        80.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        0,
        1,
        120.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        1,
        1,
        120.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        0,
        1,
        130.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        1,
        1,
        130.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        0,
        1,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        1,
        1,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        0,
        1,
        160.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        1,
        1,
        160.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        0,
        1,
        180.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        0,
        1,
        1,
        180.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        1,
        0,
        1,
        118.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        1,
        1,
        1,
        118.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        1,
        0,
        1,
        158.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        1,
        1,
        1,
        158.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        1,
        0,
        1,
        178.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        1,
        1,
        1,
        178.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        1,
        0,
        1,
        198.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        13,
        1,
        1,
        1,
        198.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        0,
        1,
        60.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        1,
        1,
        60.00,
        0,
        6
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        0,
        1,
        80.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        1,
        1,
        80.00,
        6,
        15
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        0,
        1,
        120.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        1,
        1,
        120.00,
        15,
        25
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        0,
        1,
        130.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        1,
        1,
        130.00,
        25,
        35
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        0,
        1,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        1,
        1,
        140.00,
        35,
        45
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        0,
        1,
        160.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        1,
        1,
        160.00,
        45,
        60
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        0,
        1,
        180.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        0,
        1,
        1,
        180.00,
        60,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        1,
        0,
        1,
        118.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        1,
        1,
        1,
        118.00,
        0,
        4
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        1,
        0,
        1,
        158.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        1,
        1,
        1,
        158.00,
        4,
        10
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        1,
        0,
        1,
        178.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        1,
        1,
        1,
        178.00,
        10,
        16
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        1,
        0,
        1,
        198.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        14,
        1,
        1,
        1,
        198.00,
        16,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        15,
        0,
        0,
        0,
        10.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        15,
        0,
        1,
        0,
        10.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        15,
        1,
        0,
        0,
        10.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        15,
        1,
        1,
        0,
        10.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        16,
        0,
        0,
        0,
        15.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        16,
        0,
        1,
        0,
        15.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        16,
        1,
        0,
        0,
        15.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        16,
        1,
        1,
        0,
        15.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        17,
        0,
        0,
        0,
        10.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        17,
        0,
        1,
        0,
        10.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        17,
        1,
        0,
        0,
        10.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        17,
        1,
        1,
        0,
        10.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        18,
        0,
        0,
        0,
        15.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        18,
        0,
        1,
        0,
        15.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        18,
        1,
        0,
        0,
        15.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        18,
        1,
        1,
        0,
        15.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        19,
        0,
        0,
        0,
        5.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        19,
        0,
        1,
        0,
        5.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        19,
        1,
        0,
        0,
        5.00,
        0,
        999
    );

INSERT INTO
    service_prices OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        19,
        1,
        1,
        0,
        5.00,
        0,
        999
    );