-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS shops;
CREATE TABLE shops (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  address VARCHAR(100) NOT NULL,
  longitude VARCHAR(100) NOT NULL,
  latitude VARCHAR(100) NOT NULL,
  contact VARCHAR(100) NOT NULL,
  opening_time VARCHAR(100) NOT NULL,
  closing_time VARCHAR(100) NOT NULL,
  description VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ;

INSERT INTO shops OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 'Yi Pet Store - HuiZhiShangDao', 'Room 6, No.31-6 Puhe Road, Shenbei New District, Shenyang, Liaoning, China', '123.406059', '41.944519', '+86 15142561188', '09:00', '17:00', 'Global Headquarters');