-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS spend_records;
CREATE TABLE spend_records (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  type INTEGER NOT NULL,
  record_id INTEGER NOT NULL,
  spend_amount DECIMAL(10, 2) NOT NULL,
  balance_before DECIMAL(10, 2) NOT NULL,
  balance_after DECIMAL(10, 2) NOT NULL,
  create_time VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
) ;
