-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS stock_records;
CREATE TABLE stock_records (
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER NOT NULL,
  stock_id INTEGER NOT NULL,
  change_amount INTEGER NOT NULL,
  change_reason VARCHAR(100) NOT NULL,
  change_time VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
) ;
