DROP TABLE IF EXISTS user_addresses;

CREATE TABLE user_addresses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT(11) NOT NULL,
    address_id INT(11) NOT NULL,
    is_default INT(11) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO
    user_addresses OVERRIDING SYSTEM VALUE
VALUES (DEFAULT, 3, 1, 1);

INSERT INTO
    user_addresses OVERRIDING SYSTEM VALUE
VALUES (DEFAULT, 3, 2, 0);