-- Active: 1786433062240@@127.0.0.1@5432@yipethome
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role INTEGER NOT NULL,
    shop_id INTEGER,
    avatar VARCHAR(255),
    mobile VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    balance DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO
    users OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        'admin',
        '$2b$10$kBoTOoGLt393dBdBJ1vlMeYSQ1VUmAuoqlQtErUFjnpm2krONMH72',
        0,
        0,
        NULL,
        '+64 02902574384',
        'ChandlerNZLee@outlook.com',
        'Chandler',
        'Li',
        0.0
    );

INSERT INTO
    users OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        'YiPet001',
        '$2b$10$kBoTOoGLt393dBdBJ1vlMeYSQ1VUmAuoqlQtErUFjnpm2krONMH72',
        1,
        1,
        NULL,
        '+64 0290257107',
        'ds19980331@icloud.com',
        'Daniel Steve',
        'Wang',
        0.0
    );

INSERT INTO
    users OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        'yypet',
        '$2b$10$kBoTOoGLt393dBdBJ1vlMeYSQ1VUmAuoqlQtErUFjnpm2krONMH72',
        2,
        NULL,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240704103857647.jpeg',
        '+86 15702458033',
        'BoyaDLLi@outlook.com',
        'Boya',
        'Li',
        5000.0
    );

INSERT INTO
    users OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        'steve',
        '$2b$10$kBoTOoGLt393dBdBJ1vlMeYSQ1VUmAuoqlQtErUFjnpm2krONMH72',
        2,
        NULL,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240713201155354.jpg',
        '+86 15142561188',
        'wyh980331@icloud.com',
        'Yuanheng',
        'Wang',
        5000.0
    );

INSERT INTO
    users OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        'airheaded',
        '$2b$10$kBoTOoGLt393dBdBJ1vlMeYSQ1VUmAuoqlQtErUFjnpm2krONMH72',
        2,
        NULL,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240706095804124.jpg',
        '+86 18504240436',
        'dlas@icloud.com',
        'Lu',
        'Ding',
        520.0
    );

INSERT INTO
    users OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        'guo',
        '$2b$10$kBoTOoGLt393dBdBJ1vlMeYSQ1VUmAuoqlQtErUFjnpm2krONMH72',
        2,
        NULL,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240720173849459.jpg',
        '+86 18502472492',
        'gmzsy@icloud.com',
        'Mingzhe',
        'Guo',
        1520.0
    );

INSERT INTO
    users OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        'wangdabangzi',
        '$2b$10$kBoTOoGLt393dBdBJ1vlMeYSQ1VUmAuoqlQtErUFjnpm2krONMH72',
        2,
        NULL,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20240709165953001.jpg',
        '+86 13358683532',
        'jxmas@icloud.com',
        'Ximing',
        'Jiang',
        520.0
    );

INSERT INTO
    users OVERRIDING SYSTEM VALUE
VALUES (
        DEFAULT,
        'lin',
        '$2b$10$kBoTOoGLt393dBdBJ1vlMeYSQ1VUmAuoqlQtErUFjnpm2krONMH72',
        2,
        NULL,
        'https://yypet-pictures.obs.cn-east-3.myhuaweicloud.com:443/20250515174453601.jpg',
        '+86 18652073045',
        'wlsy@icloud.com',
        'Lin',
        'Wang',
        520.0
    );